"""Declarative base + column conventions shared by every table.

Layer: models. Conventions (docs/database.md): UUIDv7 PKs, created_at /
updated_at everywhere, snake_case, plural table names.

Imported by: every module in app/models/, and by alembic/env.py through
app.models — which is what makes autogenerate see the schema.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, MetaData, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

from app.core.ids import uuid7

NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_name)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}
"""Deterministic names for every constraint and index.

Left to itself, Postgres invents names like `organizations_slug_key`, and — the
part that actually hurts — SQLAlchemy leaves unnamed constraints nameless in
metadata. Alembic then cannot reliably diff or drop them, so autogenerated
migrations either miss changes or emit `DROP CONSTRAINT None`.

This has to be set before the first table is defined. Adding it later means a
migration that renames every constraint you already have, which is exactly the
kind of churn nobody wants on a live database.
"""


class Base(DeclarativeBase):
    """The single declarative base — one MetaData for the whole application.

    Alembic autogenerate compares *one* MetaData against the database. Two
    bases means half the schema looks like it should be dropped.
    """

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class UUIDPrimaryKeyMixin:
    """A time-ordered UUID primary key, generated in Python.

    Generated client-side rather than by a database default, which means the
    id is known as soon as the row is flushed — not only after a `RETURNING`
    round trip. A service can flush a parent and its children together and
    already hold every id for logging and for wiring up foreign keys.

    Note the precise timing: `default` here is a *column* default, so SQLAlchemy
    calls `uuid7()` while building the INSERT. `Organization(...).id` is None
    until `flush()`. Making it available at construction time would mean
    mapping the class as a dataclass with `default_factory`, which is a large
    change to buy a small convenience.
    """

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid7)


class TimestampMixin:
    """`created_at` / `updated_at`, both timezone-aware and set by the database.

    Server-side defaults (`now()`) rather than Python values, because the
    database clock is the one clock every writer shares — the API, a worker and
    a psql session all have to agree on ordering.

    `DateTime(timezone=True)` maps to `timestamptz`. Plain `timestamp` stores a
    wall-clock reading with no zone, which is how audit logs end up ambiguous
    for one hour every autumn.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        # onupdate fires on ORM updates. A raw UPDATE in psql will not touch
        # it — a database trigger would cover that case too. Deliberately not
        # added yet; see docs/milestones/M2-database-layer.md.
        onupdate=func.now(),
        nullable=False,
    )
