"""`conversations` — a chat thread owned by a user within an organization.

Layer: models. The aggregate root of the chat side of the product, as
`agent_runs` is of the execution side. The two meet at
`agent_runs.conversation_id` and at `messages.agent_run_id`: one says which
thread a run belonged to, the other says which run produced a reply.

Why a thread is a row rather than a client-side grouping
--------------------------------------------------------
A chat UI could keep history in the browser and post the whole transcript with
every question. That works until the second device, the audit request, or the
first person who asks "what did the assistant tell my colleague in March". More
immediately, it makes the *client* responsible for what the model is told, which
means a client can send any history it likes — including one it invented.

The thread being server-side is what makes history a fact rather than a claim.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import DateTime, ForeignKey, Index, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, TimestampMixin, UUIDPrimaryKeyMixin

if TYPE_CHECKING:
    from app.models.message import Message

TITLE_MAX_LENGTH = 200
"""Long enough for a derived first-line title, short enough to render in a
sidebar without the UI having to truncate it a second time."""


class Conversation(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """One chat thread."""

    __tablename__ = "conversations"
    __table_args__ = (
        # "This user's threads, newest first" is the only listing that exists,
        # so the index carries the tenant, the owner and the sort key. Ordering
        # matters: `organization_id` leads because every query filters on it,
        # and a prefix of this index therefore serves an org-wide admin listing
        # without needing a second one.
        Index(
            "ix_conversations_organization_id_user_id_created_at",
            "organization_id",
            "user_id",
            "created_at",
        ),
    )

    organization_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False
    )
    """The tenant. Threads die with the organization; there is nobody left who
    may read them."""

    user_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    """Who owns the thread.

    `SET NULL`, not `CASCADE`, and for the same reason as
    `agent_runs.triggered_by`: when someone leaves, the record of what the
    assistant said on the company's behalf must outlive their account. A thread
    with no owner is still the organization's thread.
    """

    title: Mapped[str] = mapped_column(String(TITLE_MAX_LENGTH), nullable=False)
    """A human-readable label, derived from the first user message.

    Derived by code, not by a model. `docs/agents.md`: "if code can do it, code
    does it — LLM calls are for judgment, not plumbing." Truncating a sentence
    is plumbing, and an LLM-titled thread would add a model call, its latency and
    its failure mode to the act of sending a first message.
    """

    archived_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    """When the user put this thread away, or NULL while it is live.

    A timestamp rather than a boolean, because "archived" and "archived on
    Tuesday" cost the same to store and only one of them can answer a question
    later. Archiving is deliberately not deletion: the messages remain, and the
    agent runs that produced them remain auditable.

    `timezone=True` spelled out, because a bare `Mapped[datetime]` maps to
    `TIMESTAMP WITHOUT TIME ZONE` — the mistake M9's first autogenerated
    migration made on `agent_runs.started_at`.
    """

    messages: Mapped[list[Message]] = relationship(
        back_populates="conversation",
        cascade="all, delete-orphan",
        order_by="Message.created_at",
    )
    """Ordered oldest-first, which is reading order and also the order the model
    must be shown them in. `delete-orphan` so messages cannot outlive the thread
    that gives them meaning."""
