"""m16: events audit log

Revision ID: b45fbac1ed35
Revises: 041c27489c76
Create Date: 2026-08-21 00:42:03.194888

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b45fbac1ed35"
down_revision: str | None = "041c27489c76"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change.

    **The first migration since M2 with no enum to hand-drop in `downgrade()`.**
    Six milestones running (M2, M5, M9, M10, M11, M12) shipped a native Postgres
    enum whose type survives `DROP TABLE`, and autogenerate has never once
    written the `DROP TYPE` line. `events.event_type` is a plain `String(64)` —
    see `EventType` for why an audit vocabulary that grows with every feature is
    the wrong shape for a native enum — so the generated downgrade below is
    complete as written.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("actor_agent_run_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_agent_run_id"],
            ["agent_runs.id"],
            name=op.f("fk_events_actor_agent_run_id_agent_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_events_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_events_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
    )
    op.create_index(
        "ix_events_actor_user_id_created_at",
        "events",
        ["actor_user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_events_event_type_created_at", "events", ["event_type", "created_at"], unique=False
    )
    op.create_index(
        "ix_events_organization_id_created_at",
        "events",
        ["organization_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change.

    Autogenerate writes this for you, but read it before trusting it: a
    downgrade that drops a column is a downgrade that destroys data. For
    destructive changes the honest answer is often `raise NotImplementedError`
    plus a restore-from-backup runbook.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_events_organization_id_created_at", table_name="events")
    op.drop_index("ix_events_event_type_created_at", table_name="events")
    op.drop_index("ix_events_actor_user_id_created_at", table_name="events")
    op.drop_table("events")
    # ### end Alembic commands ###
