"""conversations, messages and memories

Revision ID: 04c00ca75710
Revises: 061a85cb8f80
Create Date: 2026-08-15 01:34:26.220305

"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "04c00ca75710"
down_revision: str | None = "061a85cb8f80"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

RUN_STATUS_LABELS = {
    "RUNNING": "running",
    "PAUSED_FOR_APPROVAL": "paused_for_approval",
    "SUCCEEDED": "succeeded",
    "FAILED": "failed",
    "CANCELLED": "cancelled",
}
"""M9's `run_status` labels, and what they should have been.

M9 declared `Enum(RunStatus, ...)` without `values_callable`, so SQLAlchemy
persisted member *names*. Nothing broke, because it reads them back by the same
rule — but it made `run_status` the only enum in the schema storing uppercase,
while `membership_role`, `document_status`, `document_source` and `task_status`
all store the lowercase value, each with a comment saying why.

The cost is invisible until somebody writes SQL by hand: `WHERE status =
'running'` returns zero rows and raises nothing, and `docs/database.md`
documents the lowercase form. `ALTER TYPE ... RENAME VALUE` relabels in place —
existing rows follow the label, so no data moves and no table is rewritten.
"""


def upgrade() -> None:
    """Apply the schema change."""
    # Not autogenerated: Alembic diffs tables and columns, never enum *labels*,
    # so this rename is invisible to `alembic check` in both directions. It has
    # to be written by hand and confirmed by reading `pg_enum`.
    for old, new in RUN_STATUS_LABELS.items():
        op.execute(f"ALTER TYPE run_status RENAME VALUE '{old}' TO '{new}'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversations",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_conversations_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_conversations_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
    )
    op.create_index(
        "ix_conversations_organization_id_user_id_created_at",
        "conversations",
        ["organization_id", "user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "memories",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("scope", sa.Enum("org", "user", name="memory_scope"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("content", sa.String(length=500), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
        sa.Column("importance", sa.Float(), nullable=False),
        sa.Column("last_accessed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_run_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(scope = 'user' AND user_id IS NOT NULL) OR scope = 'org'",
            name=op.f("ck_memories_user_scope_has_user"),
        ),
        sa.CheckConstraint(
            "importance >= 0 AND importance <= 1", name=op.f("ck_memories_importance_range")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_memories_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_run_id"],
            ["agent_runs.id"],
            name=op.f("fk_memories_source_run_id_agent_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_memories_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memories")),
        sa.UniqueConstraint(
            "organization_id",
            "scope",
            "user_id",
            "content_hash",
            name="uq_memories_organization_id_scope_user_id_content_hash",
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index(
        "ix_memories_embedding_hnsw",
        "memories",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"m": 16, "ef_construction": 64},
    )
    op.create_index(
        "ix_memories_organization_id_scope", "memories", ["organization_id", "scope"], unique=False
    )
    op.create_table(
        "messages",
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role", sa.Enum("user", "assistant", "tool", name="message_role"), nullable=False
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("agent_run_id", sa.Uuid(), nullable=True),
        sa.Column("token_usage", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
            name=op.f("fk_messages_agent_run_id_agent_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_messages_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
    )
    op.create_index(
        "ix_messages_conversation_id_created_at",
        "messages",
        ["conversation_id", "created_at"],
        unique=False,
    )
    op.add_column("agent_runs", sa.Column("conversation_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_agent_runs_conversation_id_conversations"),
        "agent_runs",
        "conversations",
        ["conversation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change.

    Autogenerate writes this for you, but read it before trusting it: a
    downgrade that drops a column is a downgrade that destroys data. For
    destructive changes the honest answer is often `raise NotImplementedError`
    plus a restore-from-backup runbook.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_agent_runs_conversation_id_conversations"), "agent_runs", type_="foreignkey"
    )
    op.drop_column("agent_runs", "conversation_id")
    op.drop_index("ix_messages_conversation_id_created_at", table_name="messages")
    op.drop_table("messages")
    op.drop_index("ix_memories_organization_id_scope", table_name="memories")
    op.drop_index(
        "ix_memories_embedding_hnsw",
        table_name="memories",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"m": 16, "ef_construction": 64},
    )
    op.drop_table("memories")
    op.drop_index("ix_conversations_organization_id_user_id_created_at", table_name="conversations")
    op.drop_table("conversations")
    # ### end Alembic commands ###

    # A native Postgres enum is a *type*, and `DROP TABLE` does not drop types.
    # Left behind, the next `upgrade` fails with "type memory_scope already
    # exists" — and it fails on a database that looks clean, which is what makes
    # it hard to diagnose. Fourth milestone in a row this line has been needed
    # (M2, M5, M9, M10) and autogenerate has never once written it.
    sa.Enum(name="message_role").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="memory_scope").drop(op.get_bind(), checkfirst=True)

    # Put M9's labels back, so downgrading really does restore the previous
    # schema rather than a version of it that happens to work.
    for old, new in RUN_STATUS_LABELS.items():
        op.execute(f"ALTER TYPE run_status RENAME VALUE '{new}' TO '{old}'")
