"""integrations and oauth tokens

Revision ID: 8b9d4d253f41
Revises: 04c00ca75710
Create Date: 2026-08-15 02:40:46.967187

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8b9d4d253f41"
down_revision: str | None = "04c00ca75710"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "integrations",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum(
                "gmail",
                "google_calendar",
                "google_drive",
                "slack",
                "notion",
                "github",
                "stripe",
                name="integration_provider",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("active", "revoked", "disconnected", name="integration_status"),
            nullable=False,
        ),
        sa.Column("connected_by", sa.Uuid(), nullable=True),
        sa.Column("scopes", sa.ARRAY(sa.String(length=200)), nullable=False),
        sa.Column("external_account_id", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["connected_by"],
            ["users.id"],
            name=op.f("fk_integrations_connected_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_integrations_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integrations")),
        sa.UniqueConstraint("id", "organization_id", name="uq_integrations_id_organization_id"),
    )
    op.create_index(
        "ix_integrations_organization_id_status",
        "integrations",
        ["organization_id", "status"],
        unique=False,
    )
    op.create_index(
        "uq_integrations_organization_id_provider_active",
        "integrations",
        ["organization_id", "provider"],
        unique=True,
        postgresql_where="status = 'active'",
    )
    op.create_table(
        "oauth_tokens",
        sa.Column("integration_id", sa.Uuid(), nullable=False),
        sa.Column("access_token", sa.Text(), nullable=False),
        sa.Column("refresh_token", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["integration_id"],
            ["integrations.id"],
            name=op.f("fk_oauth_tokens_integration_id_integrations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_oauth_tokens")),
        sa.UniqueConstraint("integration_id", name=op.f("uq_oauth_tokens_integration_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change.

    Autogenerate writes this for you, but read it before trusting it: a
    downgrade that drops a column is a downgrade that destroys data. For
    destructive changes the honest answer is often `raise NotImplementedError`
    plus a restore-from-backup runbook.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("oauth_tokens")
    op.drop_index(
        "uq_integrations_organization_id_provider_active",
        table_name="integrations",
        postgresql_where="status = 'active'",
    )
    op.drop_index("ix_integrations_organization_id_status", table_name="integrations")
    op.drop_table("integrations")
    # ### end Alembic commands ###

    # A native Postgres enum is a *type*, and `DROP TABLE` does not drop types.
    # Left behind, the next `upgrade` fails with "type integration_provider
    # already exists" — on a database that looks clean, which is what makes it
    # hard to diagnose. Fifth milestone in a row this line has been needed
    # (M2, M5, M9, M10, M11), and autogenerate has never once written it.
    sa.Enum(name="integration_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="integration_provider").drop(op.get_bind(), checkfirst=True)
