"""approvals

Revision ID: 041c27489c76
Revises: 8b9d4d253f41
Create Date: 2026-08-16 00:53:08.215562

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "041c27489c76"
down_revision: str | None = "8b9d4d253f41"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "approvals",
        sa.Column("agent_run_id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("requested_action", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "approved", "rejected", "expired", name="approval_status"),
            nullable=False,
        ),
        sa.Column("decided_by", sa.Uuid(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("summary", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
            name=op.f("fk_approvals_agent_run_id_agent_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["decided_by"],
            ["users.id"],
            name=op.f("fk_approvals_decided_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_approvals_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approvals")),
    )
    op.create_index(
        "ix_approvals_organization_id_status",
        "approvals",
        ["organization_id", "status"],
        unique=False,
    )
    op.create_index("uq_approvals_agent_run_id", "approvals", ["agent_run_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change.

    Autogenerate writes this for you, but read it before trusting it: a
    downgrade that drops a column is a downgrade that destroys data. For
    destructive changes the honest answer is often `raise NotImplementedError`
    plus a restore-from-backup runbook.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_approvals_agent_run_id", table_name="approvals")
    op.drop_index("ix_approvals_organization_id_status", table_name="approvals")
    op.drop_table("approvals")
    # ### end Alembic commands ###

    # A native Postgres enum is a *type*, and `DROP TABLE` does not drop types.
    # Left behind, the next `upgrade` fails with "type approval_status already
    # exists" — on a database that looks clean, which is what makes it hard to
    # diagnose. Sixth milestone in a row this line has been needed (M2, M5, M9,
    # M10, M11, M12), and autogenerate has never once written it.
    sa.Enum(name="approval_status").drop(op.get_bind(), checkfirst=True)
