"""documents and background tasks

Revision ID: 6bc020807cb8
Revises: 5159b9b65a25
Create Date: 2026-08-12 21:12:05.681617

M5. Adds `documents` (file metadata; bytes live in object storage) and `tasks`
(the durable mirror of the arq queue).

Hand-edited after autogenerate, for the reason M2 discovered the hard way: a
native PostgreSQL enum is a *type*, not part of the table that uses it, so
`DROP TABLE` leaves it behind. Autogenerate does not notice. The result is a
downgrade that appears to succeed and an upgrade that then fails with
`type "document_status" already exists` — a broken rollback discovered at the
worst possible moment, which is during a rollback.

The three `sa.Enum(...).drop(...)` calls at the end of `downgrade()` are the
fix. Verified by actually running `alembic downgrade base && alembic upgrade
head`, not by reading the code.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6bc020807cb8"
down_revision: str | None = "5159b9b65a25"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("uploaded_by", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column(
            "source",
            sa.Enum("upload", "gmail", "drive", "notion", name="document_source"),
            nullable=False,
        ),
        sa.Column("mime_type", sa.String(length=255), nullable=False),
        sa.Column("storage_uri", sa.String(length=1024), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "processing", "ready", "failed", name="document_status"),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_documents_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
            name=op.f("fk_documents_uploaded_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
    )
    op.create_index(
        "ix_documents_organization_id_status",
        "documents",
        ["organization_id", "status"],
        unique=False,
    )
    op.create_table(
        "tasks",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=100), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum("queued", "running", "succeeded", "failed", name="task_status"),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_tasks_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
    )
    op.create_index(
        "ix_tasks_organization_id_status", "tasks", ["organization_id", "status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the schema change.

    Autogenerate writes this for you, but read it before trusting it: a
    downgrade that drops a column is a downgrade that destroys data. For
    destructive changes the honest answer is often `raise NotImplementedError`
    plus a restore-from-backup runbook.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tasks_organization_id_status", table_name="tasks")
    op.drop_table("tasks")
    op.drop_index("ix_documents_organization_id_status", table_name="documents")
    op.drop_table("documents")
    # ### end Alembic commands ###

    # Hand-added. See the module docstring: dropping the tables does not drop
    # the enum types they used, and the next upgrade would fail on a type that
    # already exists. `checkfirst=False` on purpose — if one of these is
    # missing, something has already gone wrong and it should be loud.
    for enum_name in ("task_status", "document_status", "document_source"):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=False)
